name: Sync labels
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: |
            project-kkini/kkini-server
            project-kkini/front
            project-kkini/.github
          token: ${{ secrets.PERSONAL_TOKEN }}